---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Raspberry Pi OS (Debian/Bullseye)
    package:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"

