---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: install php for Apache
    apt:
      name: libapache2-mod-php
      state: absent
